//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// MFCApplication2.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_MFCApplication2TYPE         130
#define IDB_Character                   312
#define IDB_Potato                      313
#define IDB_PNG1                        316
#define IDB_Shop                        318
#define IDB_Soil                        319
#define IDB_Farm                        321
#define IDB_Village                     322
#define IDB_House                       323
#define IDB_VillageHall                 324
#define IDB_Smithy                      325
#define IDB_Cabbage                     326
#define IDB_Carrot                      327
#define IDB_Corn                        328
#define IDB_Golden_Carrot               329
#define IDB_Green_Onion                 330
#define IDB_Melon                       331
#define IDB_Radish                      332
#define IDB_Sprouted_Sweet_Potato       333
#define IDB_Strawberry                  334
#define IDB_Sweet_Potato                335
#define IDB_Watermelon                  336
#define IDB_Wheat                       337
#define IDB_White_Melon                 338
#define IDB_UI                          339
#define IDB_HallMap                     340
#define IDB_HouseMap                    341
#define IDB_WettedSoil                  343
#define IDB_ShopInner                   344
#define IDB_Wall                        345
#define IDB_HP_Potion                   346
#define IDB_MP_Potion                   347
#define IDB_Strawberry_Seed             348
#define IDB_Radish_Seed                 349
#define IDB_Raspberry_Seed              350
#define IDB_Seedless_WaterMelon_Seed    351
#define IDB_WaterMelon_Seed             352
#define IDB_Spinach_Seed                353
#define IDB_Sprouted_Potatoes_Seed      354
#define IDB_Sprouted_Sweet_Potatoe_Seed 355
#define IDB_Sprouted_Sweet_Potato_Seed  355
#define IDB_Sativus_Seed                356
#define IDB_Cabbage_Seed                357
#define IDB_Corn_Seed                   358
#define IDB_Green_Onion_Seed            359
#define IDB_White_Melon_Seed            360
#define IDB_Golden_Carrot_Seed          361
#define IDB_Potato_Seed                 362
#define IDB_Sweet_Potato_Seed           363
#define IDB_Carrot_Seed                 364
#define IDB_Melon_Seed                  365
#define IDB_Wheat_Seed                  366
#define IDB_Raspberry                   367
#define IDB_Sativus                     368
#define IDB_Seedless_Watermelon         369
#define IDB_Spinach                     370
#define IDB_SproutedPotato              371
#define IDB_Level1NonWatered            372
#define IDB_Level1Watered               373
#define IDB_Level2NonWatered            374
#define IDB_Level2Watered               375
#define IDB_Level3Cabbage               376
#define IDB_Level3Carrot                377
#define IDB_Level3Corn                  378
#define IDB_Level3GoldenCarrot          379
#define IDB_Level3GreenOnion            380
#define IDB_Level3Melon                 381
#define IDB_Level3Potato                382
#define IDB_Level3Radish                383
#define IDB_Level3Raspberry             384
#define IDB_Level3Sativus               385
#define IDB_Level3Spinach               386
#define IDB_Level3Strawberry            387
#define IDB_Level3SweetPotato           388
#define IDB_Level3WateredCabbage        389
#define IDB_Level3WateredCarrot         390
#define IDB_Level3WateredCorn           391
#define IDB_Level3WateredGoldenCarrot   392
#define IDB_Level3WateredMelon          393
#define IDB_Level3WateredPotato         394
#define IDB_Level3WateredRadish         395
#define IDB_Level3WateredRaspberry      396
#define IDB_Level3WateredSativus        397
#define IDB_Level3WateredSpinach        398
#define IDB_Level3WateredStrawberry     399
#define IDB_Level3WateredSweetPotato    400
#define IDB_Level3WateredWatermelon     401
#define IDB_Level3WateredWheat          402
#define IDB_Level3WateredWhiteMelon     403
#define IDB_Level3Watermelon            404
#define IDB_Level3Wheat                 405
#define IDB_Level3WhiteMelon            406
#define IDB_WaterCan                    407
#define IDB_Cave                        408
#define IDB_Board                       409
#define IDB_2_1                         410
#define IDB_5_3                         411
#define IDB_3_3                         412
#define IDB_5_2                         413
#define IDB_5_1                         414
#define IDB_4_2                         415
#define IDB_5_5                         416
#define IDB_4_3                         417
#define IDB_2_3                         419
#define IDB_2_2                         420
#define IDB_2_4                         421
#define IDB_4_4                         422
#define IDB_3_4                         423
#define IDB_1_4                         424
#define IDB_1_2                         425
#define IDB_1_3                         426
#define IDB_1_1                         427
#define IDB_2_5                         428
#define IDB_4_1                         429
#define IDB_3_1                         430
#define IDB_3_5                         431
#define IDB_3_2                         432
#define IDB_1_5                         433
#define IDB_4_5                         434
#define IDB_5_4                         435
#define IDB_Sword_5                     436
#define IDB_Sword_4                     437
#define IDB_Sword_3                     438
#define IDB_Sword_2                     439
#define IDB_Sword_1                     440
#define IDB_Armor_2                     441
#define IDB_Armor_1                     442
#define IDB_Armor_3                     443
#define IDB_Armor_5                     444
#define IDB_Armor_4                     445
#define IDB_BK                          446
#define IDB_Revival                     447
#define IDB_Prologue1                   448
#define IDB_Prologue2                   449
#define IDB_Prologue3                   450
#define IDB_Prologue4                   451
#define IDB_Prologue5                   452
#define IDB_Prologue6                   453
#define IDB_Prologue7                   454
#define IDB_Prologue8                   455
#define IDB_Prologue9                   456
#define IDB_Prologue10                  457
#define IDB_Prologue11                  458
#define IDB_Prologue12                  459
#define IDB_Prologue13                  460
#define IDB_Prologue14                  461
#define IDB_Prologue15                  462
#define IDB_BITMAP1                     469
#define IDB_InnerSmithy                 469
#define IDB_BITMAP2                     470
#define IDB_startScreen                 470
#define IDB_BossItem5                   471
#define IDB_BITMAP4                     472
#define IDB_BossItem1                   472
#define IDB_BossItem2                   473
#define IDB_BossItem3                   474
#define IDB_BossItem4                   475
#define IDB_Frame                       476
#define IDB_Frame_Burn                  477
#define IDB_Frame_Paralyze              478
#define IDB_Frame_Poison                479
#define IDB_Frame2                      480
#define IDB_WalkCharacter1              481
#define IDB_WalkCharacter2              482
#define IDB_Panaacea                    483
#define IDB_Fertilizer                  484
#define IDB_Fountain                    485
#define IDB_Attack1_1                   486
#define IDB_Attack1_2                   487
#define IDB_Attack1_3                   488
#define IDB_Attack1_4                   489
#define IDB_Attack1_5                   490
#define IDB_Attack1_6                   491
#define IDB_Attack1_7                   492
#define IDB_Attack2_1                   493
#define IDB_Attack2_2                   494
#define IDB_Attack2_3                   495
#define IDB_Attack2_4                   496
#define IDB_Attack2_5                   497
#define IDB_Attack2_6                   498
#define IDB_Attack2_7                   499
#define IDB_Attack3_1                   500
#define IDB_Attack3_2                   501
#define IDB_Attack3_3                   502
#define IDB_Attack3_4                   503
#define IDB_Attack3_5                   504
#define IDB_Attack3_6                   505
#define IDB_Attack3_7                   506
#define IDB_Attack4_1                   507
#define IDB_Attack4_2                   508
#define IDB_Attack4_3                   509
#define IDB_Attack4_4                   510
#define IDB_Attack4_5                   511
#define IDB_Attack4_6                   512
#define IDB_Attack4_7                   513
#define IDB_Attack4_8                   514
#define IDB_Attack4_9                   515
#define IDB_Attack5_1                   516
#define IDB_Attack5_2                   517
#define IDB_Attack5_3                   518
#define IDB_Attack5_4                   519
#define IDB_Attack5_6                   520
#define IDB_Attack5_5                   521
#define IDB_Attack5_7                   522
#define IDB_Attack5_8                   523
#define IDB_Attack5_9                   524
#define IDB_Attack5_10                  525
#define IDB_Attack5_11                  526
#define IDB_Attack5_12                  527
#define IDB_Attack5_13                  528
#define IDB_Attack5_14                  529
#define IDB_Attack5_15                  530
#define IDB_Attack5_16                  531
#define IDB_d1_1                        532
#define IDB_d1_2                        533
#define IDB_d1_3                        534
#define IDB_d1_4                        535
#define IDB_d1_5                        536
#define IDB_d2_1                        537
#define IDB_d2_2                        538
#define IDB_d2_3                        539
#define IDB_d2_4                        540
#define IDB_d2_5                        541
#define IDB_d3_1                        542
#define IDB_d3_2                        543
#define IDB_d3_3                        544
#define IDB_d3_4                        545
#define IDB_d3_5                        546
#define IDB_d4_1                        547
#define IDB_d4_2                        548
#define IDB_d4_3                        549
#define IDB_d4_4                        550
#define IDB_d4_5                        551
#define IDB_d5_1                        552
#define IDB_d5_2                        553
#define IDB_d5_3                        554
#define IDB_d5_4                        555
#define IDB_d5_5                        556
#define IDB_startScreen2                557
#define IDB_Unlock1                     558
#define IDB_Unlock2                     559
#define IDB_Unlock3                     560
#define IDB_Unlock4                     561
#define IDB_Unlock5                     562
#define IDB_Unlock6                     563
#define IDB_Ending1                     564
#define IDB_Engind2                     565
#define IDB_Ending2                     565
#define IDB_Ending3                     566
#define IDB_Ending4                     567

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        568
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
